apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: {{ template "pod.name" . }}
  name: nginx
spec:
  containers:
  - image: {{ template "pod.name" . }}
    name: {{ .Values.image }}