apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pdName }}
  labels:
{{- include "12_nexus.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes: {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ""
  {{- else }}
    storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ template "12_nexus.fullname" . }}-data