kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "12_nexus.fullname" . }}-data
  labels:
{{- include "12_nexus.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}