apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template pvcdata . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template pvclog . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template pvcconfig . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.size }}