apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template pvdata . }}
  labels:
    type: {{ template fullname . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  capacity:
    storage: {{ .Values.nfs.datasize }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: {{ template pvcdata . }}
  hostPath:
    path: "/mnt/nfs/gitlab/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template pvlog . }}
  labels:
    type: {{ template fullname . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  capacity:
    storage: {{ .Values.nfs.logsize }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: {{ template pvclog . }}
  hostPath:
    path: "/mnt/nfs/gitlab/log"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template pvconfig . }}
  labels:
    type: {{ template fullname . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  capacity:
    storage: {{ .Values.nfs.configsize }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: {{ template pvcconfig . }}
  hostPath:
    path: "/mnt/nfs/gitlab/config"