apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template pvc-data . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template pvc-log . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template pvc-config . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfs.size }}