apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "pvname" . }}
  labels:
    type: {{ template "fullname" . }}
spec:
  storageClassName: {{ .Values.nfs.name }}
  capacity:
    storage: {{ .Values.nfs.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nfs/demo"