apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: {{ template "name" . }}
  name: {{ template "fullname" . }}
spec:
  containers:
  - image: busybox
    name: {{ template "fullname" . }}