apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-0
    namespace: efk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: elasticsearch-master-elasticsearch-master-0    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-1
    namespace: efk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: elasticsearch-master-elasticsearch-master-1