apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.nfsname }}
provisioner: {{ .Values.provisioner}}  
parameters:
  archiveOnDelete: "false"
volumeBindingMode: WaitForFirstConsumer