apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.nfsname }}
  namespace: {{ .Values.namespace }}
provisioner: nfs
parameters:
  archiveOnDelete: "false"
volumeBindingMode: WaitForFirstConsumer