apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
type: Opaque
data:
  mysql-root-password: {{ include "root.password" . | b64enc | quote }}
  mysql-database: {{ include "database.name" . | base64 | quote }}
  mysql-user: {{ include "user.name" . | base64 | quote }}
  mysql-password: {{ include "user.password" . | base64 | quote }}